name      : Alexandre Rio
url       : alexrio.fr
highlighter  : rouge
include   : ['.htaccess']
exclude   : ['publish.sh', 'assets', 'publish_assets.lftp', 'publish_posts.lftp']
permalink : date
gems:
  - jekyll-gist
